Description: GIBS Dashboard
Parameters:
  WebBucket:
    Type: String
    Description: Name of the bucket to use for web content
    # A default has to be provided and is replaced at runtime due to this AWS cli bug.
    # https://github.com/aws/aws-cli/issues/2460
    Default: '%WebBucket%'
Resources:
  # S3 Bucket that hosts the content of the website.
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${WebBucket}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error
        # This is a single page app. Every path is handled within the index.html. We redirect 404s
        # to the index page but change the path to start with # to make it a hash parameter. There
        # is code within the JavaScript to fix the browser history after it loads.
        # Based on various solutions described here: http://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: '404'
            RedirectRule:
              ReplaceKeyPrefixWith: "#/"
Outputs:
  WebsiteURL:
    Value: !GetAtt HostingBucket.WebsiteURL
    Description: URL for the website hosted on S3
    Export:
      Name: WebsiteURL