Description: GIBS-in-the-Cloud
Parameters:
  DeployWorldview:
    Description: If "true", deploy a local instance of worldview in each onearth docker container
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PaaS:
    Description: If "true" the deployment is happening into the NGAP PaaS where possible
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  IngestDesiredInstances:
    Description: Number of instances to launch in the ingest ECS cluster.
    Type: Number
    Default: '1'
  IngestMaxInstances:
    Type: Number
    Default: '5'
    Description: Maximum number of instances in the ingest ECS cluster.
  IngestInstanceType:
    Description: The EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
  OnEarthStackName:
    Type: String
    Description: Name of the OnEarth stack name being created
  OnEarthMaxInstances:
    Default: '10'
    Description: Maximum number of OnEarth instances to keep.
    Type: Number
  OnEarthMinInstances:
    Default: '2'
    Description: Minimum number of OnEarth instances to keep.
    Type: Number
  Environment:
    Description: Env name associated with this deployment (e.g. DEV, SIT, UAT, OPS)
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - SIT
      - UAT
      - OPS
  VPC:
    Type: String
    Description: ID of the VPC into which we should deploy.

Resources:
  IngestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ConfigS3Bucket: !Ref ConfigBucket
        StackName: !Ref AWS::StackName
        IngestDesiredInstances: !Ref IngestDesiredInstances
        IngestMaxInstances: !Ref IngestMaxInstances
        IngestInstanceType: !Ref IngestInstanceType
        VPC: !Ref VPC
      TemplateURL: !Sub "https://s3.amazonaws.com/${ConfigBucket}/ingest/cloudformation.yml"

  APIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PaaS: !Ref PaaS
        StackName: !Ref AWS::StackName
        OnEarthStackName: !Ref OnEarthStackName
      TemplateURL: "../gibs-ops-api/config/cloudformation.yml"

  PublicUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-public-update

  PublicUpdateTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: !Sub "${AWS::StackName}PublishPolicy"
        Version: '2012-10-17'
        Statement:
          - Sid: !Sub "${AWS::StackName}PublishStmt"
            Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource: !Ref PublicUpdateTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:::${AWS::StackName}-public
      Topics:
        - Ref: PublicUpdateTopic

  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-deploy

  PrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-private
    DeletionPolicy: Retain
    Condition: IsNotDev

  PublicBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - PublicUpdateTopicPolicy
    Properties:
      BucketName: !Sub ${AWS::StackName}-public
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref PublicUpdateTopic
    DeletionPolicy: Retain
    Condition: IsNotDev

  # Hack because of this limitation on CF: https://forums.aws.amazon.com/message.jspa?messageID=560586
  DevPrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-private
    Condition: IsDev

  DevPublicBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - PublicUpdateTopicPolicy
    Properties:
      BucketName: !Sub ${AWS::StackName}-public
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref PublicUpdateTopic
    Condition: IsDev

Conditions:
  IsDev: !Equals [!Ref Environment, "DEV"]
  IsNotDev: !Not [!Equals [!Ref Environment, "DEV"]]
  IsNotPaaS: !Not [!Equals [!Ref PaaS, "true"]]

Outputs:
  ApiElasticEndpoint:
    Description: Elastic search host
    Value: !GetAtt [APIStack, Outputs.ElasticEndpoint]

  ApiUrl:
    Condition: IsNotPaaS
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !GetAtt [APIStack, Outputs.ApiUrl]
