providers:
  - id: MODAPS
    config:
      global_connection_limit: 50
  - id: LARC
    config: {}

_templates:
  _collection_types:
    - &VIIRS
      provider_id: MODAPS

      workflow: discover_VIIRS

      trigger:
        type: timer
        period_s: 900

      task_config:
        DiscoverHttpTiles:
          type: apache-index
          connections: 10
          root: 'https://lance3.modaps.eosdis.nasa.gov/imagery/elements/VIIRS/{meta.collection}/'
          match: 'https://lance3.modaps.eosdis.nasa.gov/imagery/elements/VIIRS/{meta.collection}/{_}/{jday}/{file}.{ext}'
          required:
            -
              group: file
              prop: ext
              values:
                - jgw
                - jpg
                - txt
          group_meta:
            key: 'VIIRS/{meta.collection}/{match.jday}'
            date:
              type: date
              value: '{match.jday}'
          group_by: 'VIIRS/{meta.collection}/{match.jday}'

        TriggerIngest:
          workflow: ingest_VIIRS

        SyncHttpUrls:
          connections: 5
          output:
            bucket: '{resources.buckets.private}'
            key_prefix: 'sources/EPSG{meta.epsg}/{meta.key}'

        MRFGen:
          date: '{meta.date}'
          epsg: '{meta.epsg}'
          zoom: '{meta.zoom}'
          mrfgen:
            mrf_compression_type: JPEG
            source_epsg: '{meta.epsg}'
            mrf_merge: false
            mrf_nocopy: true
            overview_resampling: average
            resize_resampling: average
            parameter_name: '{meta.parameter_name}'
          output:
            bucket: '{resources.buckets.public}'
            key_prefix: 'EPSG{meta.epsg}/{meta.collection}/{meta.date.year}'

    - &MOPITT
      provider_id: LARC

      trigger:
        type: timer
        period_s: 900
        entry: discover_MOPITT

      step_config:
        DiscoverCmrGranules:
          root: 'https://cmr.earthdata.nasa.gov'
          since: 5d
          event: wms-map-found
          granule_meta:
            key: '{meta.collection}/{granule.id}'
            granuleId: '{granule.id}'
            version: '{granule.updated}'
            date:
              type: date
              value: '{granule.time_start}'
          filename: '{meta.key}.png'
          getmap: 'https://opendap.larc.nasa.gov/ncWMS-2.0/wms?REQUEST=GetMap&VERSION=1.3.0&STYLES={meta.wms.style}&CRS=CRS:84&WIDTH=640&HEIGHT=320&FORMAT=image/png&TRANSPARENT=true&LAYERS={meta.wms.layer}&BBOX=-180,-90,180,90&&time={meta.date.isoDateTime}'
          ignoredErrorStatuses: '500'

        TriggerIngest:
          workflow: ingest_MOPITT

        SyncHttpUrls:
          connections: 5
          output:
            bucket: '{resources.buckets.private}'
            key_prefix: 'sources/EPSG{meta.epsg}/{meta.key}'

        MRFGen:
          files:
            - Bucket: '{resources.buckets.config}'
              Key: 'ingest/colormaps/{meta.colormap}'
            - Bucket: '{resources.buckets.config}'
              Key: 'ingest/empty_tiles/{meta.collection}.png'
            - filename: '{meta.granuleId}.pgw'
              contents: "0.5625\n0\n0\n-0.5625\n-179.4375\n89.4375"
          mrfgen:
            mrf_compression_type: PPNG
            source_epsg: '{meta.epsg}'
            mrf_merge: false
            mrf_nocopy: false
            overview_resampling: nearest
            resize_resampling: near
            parameter_name: '{meta.collection}'
            colormap: '{{{paths.input}}}/{meta.colormap}'
            mrf_empty_tile_filename: '{{{paths.input}}}/{meta.collection}.png'
          output:
            Bucket: '{resources.buckets.public}'
            Key: 'EPSG{meta.epsg}/{meta.collection}/{meta.date.year}'



workflows:
  discover_VIIRS:
    Comment: VIIRS Discovery
    StartAt: DiscoverHttpTiles
    States:
      DiscoverHttpTiles:
        Type: Task
        Resource: !GitcResource DiscoverHttpTilesTask
        Next: TriggerIngest

      TriggerIngest:
        Type: Task
        Resource: !GitcResource TriggerIngestTask
        End: true

  ingest_VIIRS:
    Comment: VIIRS Ingest
    StartAt: SyncHttpUrls
    States:
      SyncHttpUrls:
        Type: Task
        Resource: !GitcResource SyncHttpUrlsTask
        Next: ChooseSyncContinuation
      ChooseSyncContinuation:
        Type: Choice
        Choices:
          - Variable: $.exception
            StringEquals: NotNeeded
            Next: NoUpdates
          - Variable: $.exception
            StringEquals: Incomplete
            Next: SyncHttpUrls
          - Variable: $.exception
            StringEquals: None
            Next: MRFGen
        Default: UnhandledSyncError
      UnhandledSyncError:
        Type: Fail
        Cause: Unhandled Sync Error
      MRFGen:
        Type: Task
        Resource: !GitcResource GenerateMrfTask
        End: true
      MethodNotFound:
        Type: Fail
        Cause: Ingest Method Not Found
      NoUpdates:
        Type: Pass
        Result: No Updates Necessary
        End: true

    discover_MOPITT:
      Comment: MOPITT Discovery
      StartAt: DiscoverCmrGranules
      States:
        DiscoverCmrGranules:
          Type: Task
          Resource: !GitcResource DiscoverCmrGranulesTask
          Next: TriggerIngest

        TriggerIngest:
          Type: Task
          Resource: !GitcResource TriggerIngestTask
          End: true

    ingest_MOPITT:
      Comment: MOPITT Ingest
      StartAt: CreateWmsUrls
      States:
        CreateWmsUrls:
          Type: Task
          Resource: !GitcResource SyncWmsTask
          Next: SyncHttpUrls
        SyncHttpUrls:
          Type: Task
          Resource: !GitcResource SyncHttpUrlsTask
          Next: ChooseSyncContinuation
        ChooseSyncContinuation:
          Type: Choice
          Choices:
            - Variable: $.exception
              StringEquals: NotNeeded
              Next: NoUpdates
            - Variable: $.exception
              StringEquals: Incomplete
              Next: SyncHttpUrls
            - Variable: $.exception
              StringEquals: None
              Next: MRFGen
          Default: UnhandledSyncError
        UnhandledSyncError:
          Type: Fail
          Cause: Unhandled Sync Error
        MRFGen:
          Type: Task
          Resource: !GitcResource GenerateMrfTask
          End: true
        MethodNotFound:
          Type: Fail
          Cause: Ingest Method Not Found
        NoUpdates:
          Type: Pass
          Result: No Updates Necessary
          End: true


collections:
  - <<: *VIIRS
    id: VNGCR_LQD_C1
    meta:
      collection: VNGCR_LQD_C1
      parameter_name: VNGCR_LQD_I1-M4-M3_NRT
      epsg: 4326
      zoom: 9

  - <<: *VIIRS
    id: VNGCR_SQD_C1
    meta:
      collection: VNGCR_SQD_C1
      parameter_name: VNGCR_SQD_I1-M4-M3_NRT
      epsg: 3031
      zoom: 6

  - <<: *VIIRS
    id: VNGCR_NQD_C1
    meta:
      collection: VNGCR_NQD_C1
      parameter_name: VNGCR_NQD_I1-M4-M3_NRT
      epsg: 3413
      zoom: 6

  - <<: *MOPITT
    id: MOPITT_DCOSMR_LL_D_STD
    meta:
      concept_id: C190698050-LARC
      collection: MOPITT_DCOSMR_LL_D_STD
      colormap: MOPITT_CO_Daily_Surface_Mixing_Ratio_Day.xml
      epsg: 4326
      zoom: 6
      wms:
        layer: MOP03J.006/RetrievedCOSurfaceMixingRatioDay
        style: se_mopitt_threshold_retrievedcosurfacemixingratioday_mop03j

# (Envelope)
  # task_config:
  # resources:
  # provider: (new)
  # [ingest_]meta:
  # meta:
  # exception:
  # payload: (optional)
